#import <Foundation/Foundation.h>
#import <Capacitor/Capacitor.h>

CAP_PLUGIN(DiagnosticPlugin, "DiagnosticPlugin",
    
    // -----------------------
    // General
    // -----------------------
    CAP_PLUGIN_METHOD(enableDebug, CAPPluginReturnPromise);
    // -----------------------
    // Location
    // -----------------------
    CAP_PLUGIN_METHOD(getLocationAuthorizationStatus, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(requestLocationAuthorization, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(openLocationSettings, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(switchToLocationSettings, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(isLocationEnabled, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(isLocationAvailable, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(isGpsLocationEnabled, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(isNetworkLocationEnabled, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(isGpsLocationAvailable, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(isNetworkLocationAvailable, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(getLocationMode, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(isCompassAvailable, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(isLocationAuthorized, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(getLocationAccuracyAuthorization, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(requestTemporaryFullAccuracyAuthorization, CAPPluginReturnPromise);
    // -----------------------
    // Bluetooth
    // -----------------------
    CAP_PLUGIN_METHOD(switchToBluetoothSettings, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(isBluetoothAvailable, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(isBluetoothEnabled, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(hasBluetoothSupport, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(hasBluetoothLESupport, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(hasBluetoothLEPeripheralSupport, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(setBluetoothState, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(getBluetoothState, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(getBluetoothAuthorizationStatuses, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(requestBluetoothAuthorization, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(ensureBluetoothManager, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(getBluetoothAuthorizationStatus, CAPPluginReturnPromise);
    // -----------------------
    // Camera
    // -----------------------
    CAP_PLUGIN_METHOD(isCameraPresent, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(requestCameraAuthorization, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(getCameraAuthorizationStatus, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(getCameraAuthorizationStatuses, CAPPluginReturnPromise);
    // -----------------------
    // Notifications
    // -----------------------
    CAP_PLUGIN_METHOD(isRemoteNotificationsEnabled, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(getRemoteNotificationTypes, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(isRegisteredForRemoteNotifications, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(getRemoteNotificationsAuthorizationStatus, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(requestRemoteNotificationsAuthorization, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(switchToNotificationSettings, CAPPluginReturnPromise);
    // -----------------------
    // Wifi
    // -----------------------
    CAP_PLUGIN_METHOD(isWifiAvailable, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(isWifiEnabled, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(requestLocalNetworkAuthorization, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(getLocalNetworkAuthorizationStatus, CAPPluginReturnPromise);
    // -----------------------
    // Microphone
    // -----------------------
    CAP_PLUGIN_METHOD(isMicrophoneAuthorized, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(getMicrophoneAuthorizationStatus, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(requestMicrophoneAuthorization, CAPPluginReturnPromise);
    // -----------------------
    // Motion
    // -----------------------
    CAP_PLUGIN_METHOD(isMotionAvailable, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(isMotionRequestOutcomeAvailable, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(getMotionAuthorizationStatus, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(requestMotionAuthorization, CAPPluginReturnPromise);
    // -----------------------
    // Reminders
    // -----------------------
    CAP_PLUGIN_METHOD(getRemindersAuthorizationStatus, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(isRemindersAuthorized, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(requestRemindersAuthorization, CAPPluginReturnPromise);
    // -----------------------
    // Calendar
    // -----------------------
    CAP_PLUGIN_METHOD(getCalendarAuthorizationStatus, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(isCalendarAuthorized, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(requestCalendarAuthorization, CAPPluginReturnPromise);
    // -----------------------
    // Contacts
    // -----------------------
    CAP_PLUGIN_METHOD(getAddressBookAuthorizationStatus, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(isAddressBookAuthorized, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(requestAddressBookAuthorization, CAPPluginReturnPromise);
    // -----------------------
    // System
    // -----------------------
    CAP_PLUGIN_METHOD(switchToSettings, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(isADBModeEnabled, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(isDataRoamingEnabled, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(restart, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(switchToMobileDataSettings, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(switchToWirelessSettings, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(isBackgroundRefreshAuthorized, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(enableDebug, CAPPluginReturnPromise);
)